language: cpp

python:
  - "2.7"

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      osx_image: xcode7.2
      compiler: clang

git:
  submodules: false

install:
  - git submodule update --init --recursive
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update;
      brew install python;
      brew install scons;
    fi
  - pip install --user cython
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      export PATH=~/Library/Python/2.7/bin:$PATH;
    fi
  - which python
  - which cython

script:
  - scons no-cache=1 static=1 all
  - scons no-cache=1 static=0 all

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "X+3JRFCxJi7IntGZdwTuJCkVBW2ASH6Sw81Qooqa/KeOxUPaSmrLzPZV5F9cpic5JqSfdoyQTpYCQC4lVuRN92HrrlfVuJJDmoZadv6rn2mc7SZLKF6Q/24UlkTm7n5QgBBfgDs5/Z4pDmRdQNRzz3Esrl1UVfmnhaxZLN5eFVw="

addons:
  coverity_scan:
    project:
      name: "gatgui/gcore"
      description: "Build submitted via Travis CI"
    notification_email: gatgui@gmail.com
    build_command_prepend: "git submodule update --init --recursive"
    build_command: "scons static=0 no-cache=1 gcore"
    branch_pattern: coverity-scan
